language: node_js
node_js:
- '6'
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  directories:
  - "$HOME/.npm"
env:
  global:
  - JOBS=1
before_install:
- npm config set spin false
deploy:
  provider: heroku
  api_key:
    secure: rNka2WEKSY6IOb+yACR1hr6DK8L3ut355sWFxsz70tQ+IpafSbNIBglgdDMw4bbMh/ZXnzZWqALERT++HXsUSjfJs33+H6iMB59H7z6RyPxTrp1jy2+Xri3gOTzCQcki7fry5FaA2jF94Co0OmuzNbJILpH579gIFkHeppiFXGjK8B1p+tiYiLcmQ4r537daEtloKIAA6UnDGeaL3hOZB+hiCXEJQd8Wk9yFVbOiWPbOMOI5a2BwFxZTLDeQ3DCF3sSVAiu9WYsD9xXY5wAwg0PmQ0YWJQQFA3V6IPiGAemJFvsibMVzv/iU9u5xCILJ2aejG88hDOMVmYXaINWaqPsmkrF0m1vIfvw6i2oU3m8o9X16NIuksMsdOnLim6Dt8OrnlXixaTThCFLQyrSFOL/xKl3aYOKYOQukBz2gbpErOa0hsxBu02WFMdtUtJDTc/kybfjl0CymRa3hCEkBR5DrhDNf8oe/Y4p1SNXVkcgLZApKY6VLMeMtWlWt+8ZlvyCAkoxuKn5RcCNezXkmBMHrw1UOUhOpxYWaOhTu7ERGjA/s431y7i4qJAqf8RtserObVlaeophKLCUutIfcIpGxbOfrAWhzgkWM/FKXq6IuXnlzaKNFz4qWPRFFAZw5/R35QYxxYG/zrNdX0PF6J3ktgmRcVXamq6YOEybDo9s=
