language: node_js
node_js:
- '6'
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  directories:
  - "$HOME/.npm"
env:
  global:
  - JOBS=1
before_install:
- npm config set spin false
deploy:
  provider: heroku
  api_key:
    secure: zna3I5Kx0VrPe2+ISIipG/iFGxytAxHWD0F0n8o9ADnpt+oaJ4MOxidYz+mlyf8LPoC5n5TIr5JoKBP1OQThcKn8KjBED/0A2Xd64GcKSpAf+C+NEOwhprxFvZzHKh2kQ1SEMHmz5mD23etr7A6mH7zzl/J6H9S1Ws0mChGXvYeQb/S/tTq7xAzH6UCcNosAZahvlOU7OtYKaoIp+07N6k1ol54fpZ+9ivikE7E+pNiQNrh81Br43qY+y4Aggugd/m1d4F7YKOWJsOn9TV+utzOtfCJ1xmLKWB1UzGhEFsN8NE9kGYVXlNp6DFAQdHPjdg2E4QyT/eEJOQARLqtci2QYd5YZk+O8s+JbPmRtQoDHp9/gtK2vH8qoRjCvcWbdTA9e/b6NnAC8YkMZaTTQjYaw78cOMA+jcx7EL6Xi6SvSuAbHCU/lo5KcztUzWvGfYoVsb9rIYqtWTTOwjCnsCFJqNF7aeNu52yN9Sls2NVnFiRIkqX6qSS8PNuicbKaLKamE8c7vhvXC94RjQCl+ZfXIszAlV3ZiTcuHLFxA/IosN2dnr0nFUNd6YekPkhZW63mEKXL27UFvZ5b1ksRwSPCT6e5KFy8IUHOudVel9LtJ7wa2zQt6/f9s9q8bqGdMH0ydn8Kf+zBQvcOYbJTwd24nqU4pzdSoVoSZ8bhlFt4=
