language: node_js
node_js:
- '6'
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  directories:
  - "$HOME/.npm"
env:
  global:
  - JOBS=1
before_install:
- npm config set spin false
deploy:
  provider: heroku
  api_key:
    secure: ZtAtOtx7SStjJAY/5FsOo5Whd+7sPmN3I6V8EO/YifdH35d1xrx3tqo8b3Bfi+A63WiTPCGhvP3S93e8deavQ8krrQVz/9wqHqRqeYXCYQ+dIZPN/86YiXz5zqfplpf/oo30RDpsVOnhKJKy4iw74Z4P5abc2VByN8WhSftzSVlmbRt0KJ8facqbVigH5eEq5yJp7WJGQi4P7eTpn4LRF8oyPpamIqWAWsBUBlalFICRlsSOa6GTOIb54+LndisNBuZPXeETpgmvOn6L3qRU7aQ0k9Fkr9KUslrPt9k8Qd5qZbf2ynj+/birlcJNKaNOz2Osy/1Drm3H/jt3wSRnO08o0NKFOynzrJ6pnDmqT/nfXZPfrbJz9gx11GIv/t3DOl54TAM8YC+6/UJgHSq8pUFEinyuSUeeaApXxtrtNrqfilrsRB8IYpzWT1Q5aaTUlL29zqmGvlk8MS4oLW44bwcL3DheFDIiyQ+opck+aN4ukwXEYGMr/LWifWOfTvKXYVmpCOMMDvWNPrWTo36YFxtlzUg6NEJRo2BYKqO1aGQX7aiodvmBs2nX1WCcR1GcPCkRzTP+6UMPx5U+QNAnITUiY8f6W2GX+ADuCJCSLj8Sfzt2rTO5WsRDsJuPE9Eg8yCWK5xyqe9o6FuHUrvvFQ1xKKSFPk3PFB+Xrd/WLQA=
